//
//  AppAttestService.swift
//  SIMResearch
//
//  Wraps `DCAppAttestService` — the hardware-attested key flow that
//  is, in practice, the strongest device-trust primitive iOS exposes.
//  It is the closest replacement to "we need a device identifier we
//  can't spoof": every signed assertion proves that
//
//      (a) the request was generated by an unmodified copy of THIS
//          app (binary integrity + bundle id + team id checked by
//          Apple at attestation time), and
//      (b) the signing key lives in the Secure Enclave of a real
//          Apple device (not a simulator, not an emulator, not a
//          tampered installation).
//
//  Production lifecycle, end-to-end
//  --------------------------------
//   1. App calls `generateKey()` -> `keyId`. Stored in Keychain.
//   2. App fetches a one-shot challenge from your backend.
//   3. App calls `attestKey(keyId, clientDataHash:)`. Sends the blob
//      to your backend, which validates it against Apple's servers
//      and stores `(keyId, public key, attestation)` next to the
//      customer record.
//   4. For every sensitive request, the app builds a clientData hash
//      (request method + URL + body + nonce), calls
//      `generateAssertion(keyId, clientDataHash:)`, and sends the
//      assertion alongside the request. The backend validates with
//      the previously-stored public key.
//
//  This service supports steps 1, 3, and 4. Step 2 (server challenge)
//  is faked locally for the demo and clearly marked as such in the
//  view layer.
//

import Foundation
import CryptoKit
import DeviceCheck

final class AppAttestService {

    enum AttestError: Error, LocalizedError {
        case unsupported
        case keyGenerationFailed(Error?)
        case attestationFailed(Error?)
        case assertionFailed(Error?)
        case keyMissing

        var errorDescription: String? {
            switch self {
            case .unsupported:
                return "App Attest is not supported on this device (Simulator, jailbroken device, or unsupported model)."
            case .keyGenerationFailed(let e):
                return "Key generation failed: \(e?.localizedDescription ?? "unknown error")"
            case .attestationFailed(let e):
                return "Attestation failed: \(e?.localizedDescription ?? "unknown error")"
            case .assertionFailed(let e):
                return "Assertion generation failed: \(e?.localizedDescription ?? "unknown error")"
            case .keyMissing:
                return "No App Attest key has been generated yet."
            }
        }
    }

    private let attestService = DCAppAttestService.shared
    private let keychainKeyIdAccount = "appattest-keyid.v1"
    private let keychainService: String

    init(keychainService: String? = nil) {
        self.keychainService = keychainService
            ?? Bundle.main.bundleIdentifier
            ?? "SIMResearch.AppAttestService"
    }

    /// Always `false` on Simulator. The project happens to deploy to
    /// real devices (banking) so this is the path that will be hit.
    var isSupported: Bool { attestService.isSupported }

    // MARK: - Key id storage

    /// Persisted across launches in the same Keychain device-bound
    /// slot used by `KeychainUUIDService`. The Secure Enclave private
    /// key itself never leaves the SEP; we only persist the opaque
    /// identifier needed to address it.
    func storedKeyId() -> String? {
        var query = baseQuery()
        query[kSecReturnData as String] = true
        query[kSecMatchLimit as String] = kSecMatchLimitOne
        var result: AnyObject?
        let status = SecItemCopyMatching(query as CFDictionary, &result)
        guard status == errSecSuccess, let data = result as? Data else { return nil }
        return String(data: data, encoding: .utf8)
    }

    func clearStoredKeyId() {
        SecItemDelete(baseQuery() as CFDictionary)
    }

    private func storeKeyId(_ keyId: String) {
        clearStoredKeyId()
        guard let data = keyId.data(using: .utf8) else { return }
        var attributes = baseQuery()
        attributes[kSecValueData as String] = data
        attributes[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
        SecItemAdd(attributes as CFDictionary, nil)
    }

    private func baseQuery() -> [String: Any] {
        [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: keychainService,
            kSecAttrAccount as String: keychainKeyIdAccount
        ]
    }

    // MARK: - Lifecycle

    /// Step 1 — Generate a fresh Secure Enclave key. The returned
    /// `keyId` is a base64 blob that addresses the key for future
    /// `attestKey` and `generateAssertion` calls.
    func generateKey() async throws -> String {
        guard isSupported else { throw AttestError.unsupported }
        do {
            let keyId = try await attestService.generateKey()
            storeKeyId(keyId)
            return keyId
        } catch {
            throw AttestError.keyGenerationFailed(error)
        }
    }

    /// Step 3 — Attest the key against Apple's servers with the
    /// supplied challenge. In production the challenge MUST come from
    /// your backend, single-use, anti-replay-protected.
    func attestKey(_ keyId: String, challenge: Data) async throws -> Data {
        guard isSupported else { throw AttestError.unsupported }
        let clientDataHash = Data(SHA256.hash(data: challenge))
        do {
            return try await attestService.attestKey(keyId, clientDataHash: clientDataHash)
        } catch {
            throw AttestError.attestationFailed(error)
        }
    }

    /// Step 4 — Per-request signature. `clientData` is whatever the
    /// backend needs to bind the signature to (typically: request
    /// method + URL + body bytes + a server nonce).
    func generateAssertion(keyId: String, clientData: Data) async throws -> Data {
        guard isSupported else { throw AttestError.unsupported }
        let hash = Data(SHA256.hash(data: clientData))
        do {
            return try await attestService.generateAssertion(keyId, clientDataHash: hash)
        } catch {
            throw AttestError.assertionFailed(error)
        }
    }
}
