//
//  IdentifierCatalogService.swift
//  SIMResearch
//
//  Builds the live catalog of every identifier this app can read,
//  paired with the change-trigger metadata in
//  `IdentifierLifecycle.swift`. Pulls from the existing services so
//  there is exactly one source of truth per identifier.
//

import Foundation
import UIKit
import CoreTelephony

@MainActor
final class IdentifierCatalogService {

    private let deviceInfo: DeviceInfoService
    private let simInfo: SIMInfoService
    private let keychain: KeychainUUIDService
    private let appAttest: AppAttestService
    private let deviceCheck: DeviceCheckService

    init(
        deviceInfo: DeviceInfoService = DeviceInfoService(),
        simInfo: SIMInfoService = SIMInfoService(),
        keychain: KeychainUUIDService = KeychainUUIDService(),
        appAttest: AppAttestService = AppAttestService(),
        deviceCheck: DeviceCheckService = DeviceCheckService()
    ) {
        self.deviceInfo = deviceInfo
        self.simInfo = simInfo
        self.keychain = keychain
        self.appAttest = appAttest
        self.deviceCheck = deviceCheck
    }

    /// One snapshot, ordered from most-stable to least-stable so the
    /// "best candidate for device id" rises to the top of the list.
    func currentCatalog() -> [IdentifierLifecycleEntry] {
        var entries: [IdentifierLifecycleEntry] = []

        // ─── Hardware-tied, immutable ─────────────────────────────
        let device = deviceInfo.currentSnapshot()

        entries.append(.init(
            id: "hardwareIdentifier",
            displayName: "Hardware identifier",
            sourceAPI: "uname() / utsname.machine",
            documentationURL: URL(string: "https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/uname.3.html"),
            liveValue: device.hardwareIdentifier,
            stability: .immutable,
            changedBy: [],
            notes: "Identifies the hardware model (e.g. iPhone16,1). Same value on every iPhone of this exact model. Cannot change without physically swapping the device."
        ))

        entries.append(.init(
            id: "marketingModel",
            displayName: "Marketing model",
            sourceAPI: "Mapped from utsname.machine",
            documentationURL: nil,
            liveValue: device.marketingModel,
            stability: .immutable,
            changedBy: [],
            notes: "Human-readable name (e.g. iPhone 15 Pro). Derived from the hardware identifier; same change rules."
        ))

        entries.append(.init(
            id: "systemVersion",
            displayName: "iOS version",
            sourceAPI: "UIDevice.systemVersion",
            documentationURL: URL(string: "https://developer.apple.com/documentation/uikit/uidevice/systemversion"),
            liveValue: device.systemVersion,
            stability: .perDevice,
            changedBy: [.osUpdate],
            notes: "Marketing OS version string. Changes only when iOS itself is updated (Settings → General → Software Update)."
        ))

        // ─── Per-device, survives reinstall ───────────────────────
        entries.append(.init(
            id: "keychainUUID",
            displayName: "Keychain device UUID",
            sourceAPI: "Security framework + kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly",
            documentationURL: URL(string: "https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlockthisdeviceonly"),
            liveValue: keychain.currentUUID(),
            stability: .perDevice,
            changedBy: [.factoryReset, .newDevice],
            notes: "UUID generated by this app on first launch and stored in the device-only Keychain. Survives app uninstall and reinstall on the SAME device. Never syncs to iCloud (the 'ThisDeviceOnly' suffix), so a brand-new iPhone gets a brand-new value even after iCloud restore."
        ))

        // ─── Per-Secure-Enclave-key ───────────────────────────────
        entries.append(.init(
            id: "appAttestKeyId",
            displayName: "App Attest key id",
            sourceAPI: "DCAppAttestService.generateKey()",
            documentationURL: URL(string: "https://developer.apple.com/documentation/devicecheck/dcappattestservice"),
            liveValue: appAttest.storedKeyId(),
            stability: .perSEPKey,
            changedBy: [.factoryReset, .newDevice, .differentTeam],
            notes: "Identifier of a private key in the Secure Enclave. The key cannot be extracted, only used to sign. Stays valid as long as the SEP retains it; factory reset wipes it. A new key id is generated each time `generateKey()` is called."
        ))

        // ─── Per-vendor-install (Apple's intended device id) ──────
        entries.append(.init(
            id: "identifierForVendor",
            displayName: "identifierForVendor (IDFV)",
            sourceAPI: "UIDevice.current.identifierForVendor",
            documentationURL: URL(string: "https://developer.apple.com/documentation/uikit/uidevice/identifierforvendor"),
            liveValue: UIDevice.current.identifierForVendor?.uuidString,
            stability: .perVendorInstall,
            changedBy: [.allVendorRemoved, .factoryReset, .newDevice, .differentTeam],
            notes: "Apple's intended 'one identifier per (vendor, device)'. Stable as long as ANY app from your vendor remains installed. The day a user removes the last app from your vendor and then installs one again, IDFV resets — that's documented behaviour, not a bug. Different developer teams = different vendors = different IDFV."
        ))

        // ─── Per-call (server-verifiable) ─────────────────────────
        let dcState: String
        switch deviceCheck.isSupported {
        case true:  dcState = "Supported. Tap 'Generate token' in the Trust tab."
        case false: dcState = "Not supported on this device (Simulator)."
        }
        entries.append(.init(
            id: "deviceCheckToken",
            displayName: "DeviceCheck token",
            sourceAPI: "DCDevice.generateToken()",
            documentationURL: URL(string: "https://developer.apple.com/documentation/devicecheck/dcdevice"),
            liveValue: dcState,
            stability: .perCall,
            changedBy: [.appRelaunch, .backgroundForeground, .osUpdate, .reboot, .appReinstall, .allVendorRemoved, .factoryReset, .newDevice, .differentTeam],
            notes: "The token bytes change every call, but Apple's servers consistently identify the SAME (device, developer team) pair behind them. Treat the token as opaque transport; the persistent identity lives in Apple's two device-bits per developer team, not in the token itself."
        ))

        // ─── SIM-tied ─────────────────────────────────────────────
        let simSnapshot = simInfo.currentSnapshot()
        let serviceIds = simSnapshot.subscriptions.map(\.id).joined(separator: ", ")
        entries.append(.init(
            id: "ctServiceIdentifier",
            displayName: "CoreTelephony service identifier(s)",
            sourceAPI: "CTTelephonyNetworkInfo.serviceSubscriberCellularProviders",
            documentationURL: URL(string: "https://developer.apple.com/documentation/coretelephony/cttelephonynetworkinfo"),
            liveValue: serviceIds.isEmpty ? "No active subscription" : serviceIds,
            stability: .perAppInstall,
            changedBy: [.simSwap, .factoryReset, .newDevice, .appReinstall],
            notes: "Service id per active SIM/eSIM subscription. Stable for the lifetime of the subscription. SIM swap, eSIM rotation, or carrier change produces a new id."
        ))

        // ─── Locale-related (informational; not really a 'device' id but useful) ──
        entries.append(.init(
            id: "localeIdentifier",
            displayName: "Locale identifier",
            sourceAPI: "Locale.current.identifier",
            documentationURL: URL(string: "https://developer.apple.com/documentation/foundation/locale"),
            liveValue: device.localeIdentifier,
            stability: .perDevice,
            changedBy: [.factoryReset, .newDevice],
            notes: "Changes when the user changes the device language/region in Settings — not in the trigger list because it's a user action, not a system event. Listed here so you can see which fields are user-controlled vs system-controlled."
        ))

        return entries.sorted { $0.stability > $1.stability }
    }
}
